1. Import the numpy package under the name  

In [3]:
import numpy as np

2. Print the numpy version and the configuration

In [4]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Dell/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

3. Create a null vector of size 10

In [5]:
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.  How to find the memory size of any array 

In [8]:
import numpy as np
x=np.array([7,4])
print(x.size)
print(x.itemsize)
print(x.size*x.itemsize)

2
4
8


5.  How to get the documentation of the numpy add function from the command line?

In [9]:
np.add?

6.  Create a null vector of size 10 but the fifth value which is 1

In [11]:
import numpy as np
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.  Create a vector with values ranging from 10 to 49 

In [2]:
import numpy as np
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8.  Reverse a vector (first element becomes last)

In [3]:
x=np.array([7,8,6,4,2])
print(x[::-1])

[2 4 6 8 7]


9.  Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
b=np.arange(0,9).reshape(3,3)
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from \\[1,2,0,0,4,0\\]

In [5]:
x=np.array([1,2,0,0,4,0])
x1=np.nonzero(x)
print(x1)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix

In [6]:
n=np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values 

In [8]:
c=np.random.rand(3,3,3)
print(c)

[[[0.87321743 0.22140532 0.2780078 ]
  [0.08443977 0.71612577 0.23207315]
  [0.17576813 0.51431899 0.17343812]]

 [[0.46037618 0.16670738 0.47663772]
  [0.83762997 0.04855352 0.62295101]
  [0.20786499 0.59998189 0.41245618]]

 [[0.0603227  0.41192027 0.9311927 ]
  [0.29123574 0.77308752 0.10422638]
  [0.36979368 0.75717684 0.08211916]]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
v=np.random.rand(10,10)
print(v.max())
print(v.min())

0.9877735169720858
0.009392171810820082


14. Create a random vector of size 30 and find the mean value

In [15]:
print(np.random.rand(30).mean())

0.5062022151313513


15. Create a 2d array with 1 on the border and 0 inside

In [17]:
v=np.ones((5,5))
v[1:-1,1:-1]=0
print(v)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? 

In [20]:
v=np.ones((3,3))
b=np.pad(v,pad_width=1,mode='constant',constant_values=0)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. What is the result of the following expression?

In [22]:
0 * np.nan

nan

In [26]:
np.nan == np.nan

False

In [27]:
np.inf > np.nan

False

In [34]:
np.nan - np.nan

nan

In [36]:
np.nan in set([np.nan])

True

In [37]:
0.3 == 3 * 0.1

False

 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [7]:
import numpy as np
v=np.diag([1,2,3,4],k=-1)
print(v)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (

In [11]:
v=np.zeros((8,8))
v[::2,1::2]=1
v[1::2,::2]=1
print(v)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th e

In [13]:
v=np.zeros((6,7,8))
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function 

In [19]:
arr=np.array([[0,1],[1,0]])
print(np.tile(arr,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 22. Normalize a 5x5 random matrix

In [4]:
import numpy as np
z=np.random.random((5,5))
z=z-z.min()/z.max()-z.min()
print(z)

[[ 0.29573673  0.74907674  0.46546778  0.78843294  0.15236851]
 [ 0.83938141  0.18577629  0.47428764  0.00240986  0.76660931]
 [ 0.56501396  0.87183328  0.35834625 -0.02554399  0.47352612]
 [ 0.2043252   0.10393718  0.3627226   0.5803378   0.59946894]
 [ 0.86904127  0.50099489  0.48085636  0.9404559   0.7688435 ]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [11]:
import numpy as np
color=np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),('b',np.ubyte,1),('a',np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [12]:
import numpy as np
z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [19]:
g=np.array([3,6,5,1,2])
v=(g>=3) &(g<=8)
g[v]=g[v]*-1
print(g)

[-3 -6 -5  1  2]


26. What is the output of the following script? 

In [26]:
print(sum(range(5),-1))

10


In [27]:
from numpy import *
print(sum(range(5),-1))

10


27. Consider an integer vector Z, which of these expressions are legal?

In [33]:
z=np.array([3,4],dtype=int)
c=z**z
c

array([ 27, 256], dtype=int32)

In [34]:
2 << z >> 2

array([4, 8], dtype=int32)

In [35]:
z <- z

array([False, False])

In [37]:
1j*z

array([0.+3.j, 0.+4.j])

In [39]:
z/1/1

array([3., 4.])

In [ ]:
z<z>z

What are the result of the following expressions?

In [3]:
import numpy as np
np.array(0) / np.array(0)

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


nan

In [4]:
np.array(0) // np.array(0)

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [5]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

29. How to round away from zero a float array ? 

In [8]:
import numpy as np
def round_array(x,y):
    return np.round(x,y)
t=np.array([34.66,78.9,67.8])
round_array(t,0)

array([35., 79., 68.])

30. How to find common values between two arrays? 

In [10]:
g=np.array([[4,3,2,1]])
g1=np.array([5,4,3,2])
np.intersect1d(g,g1)

array([2, 3, 4])

31. How to ignore all numpy warnings (not recommended)?

In [16]:
defaults=np.seterr(all="ignore")
z=np.ones(1)/0
_=np.seterr(**defaults)

 32. Is the following expressions true?

In [17]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. How to get the dates of yesterday, today and tomorrow?

In [22]:
from datetime import datetime,timedelta
today=datetime.now()
yes=today-timedelta(days=1)
tomo=today+timedelta(days=1)
print(today)
print(yes)
print(tomo)

2021-01-16 19:08:06.606752
2021-01-15 19:08:06.606752
2021-01-17 19:08:06.606752


34. How to get all the dates corresponding to the month of July 2016?

In [35]:
print("July","2016")

n=np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(n)

July 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)\\*(-A/2)) in place (without copy)? 

In [2]:
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


36. Extract the integer part of a random array using 5 different methods 

In [6]:
Z = np.random.uniform(0,10,10)
print (Z-Z%1)


[0.66562027 0.54799348 0.37982129 0.07412954 0.61522105 0.78037499
 0.08306113 0.12449057 0.17632936 0.16415471]
